[package]
name = "i_am_parameters_derive"
version = "0.1.0"
edition = "2024"

[dependencies]
proc-macro2 = "1.0.101"
quote = "1.0.41"
syn = { version = "2.0.106", features = ["extra-traits", "full"] }

[lib]
proc-macro = true