[package]
name = "i_am_dsp"
version = "0.1.0"
edition = "2024"

[features]
default = ["standalone"]
room_gen = ["parry3d"]
sin_table = []
standalone = ["eframe", "real_time_demo", "cpal"]
real_time_demo = ["egui", "anyhow", "egui_file"]
rhai = ["dep:rhai", "dep:rhai-rand"]

[dependencies]
i_am_dsp_derive.workspace = true

anyhow = { version = "1.0.104", optional = true }
bitvec = "1.1.1"
cpal = { version = "0.18.2", optional = true }
crossbeam-channel = "0.5.16"
eframe = { version = "0.36", optional = true }
egui = { version = "0.36", optional = true }
lazy_static = "1.5.0"
rand = "0.10.2"
rand_distr = "0.6.0"
# rayon = "1.11.0"
rhai = { version = "1.25.1", features = ["f32_float", "sync", "only_i32"], optional = true }
rhai-rand = { version = "0.2.0", optional = true }
rubato = "5.0.0"
rustfft = "6.4.1"
symphonia = "0.6.1"
thiserror = "2.0.20"
cfg-if = "1.0.4"
serde = { version = "1.0.229", features = ["derive"] }
ciborium = "0.2.2"
# threadpool = "1.8.1"
hound = "3.5.1"
parry3d = { version = "0.30.2", optional = true }
egui_file = { version = "0.28", optional = true }
wide = "1.6.1"
# fft-convolver = "0.2.0"
portable-atomic = { version = "1.15.0", features = ["float", "serde"] }
bimap = "0.6.3"
phf = { version = "0.14.0", features = ["macros"] }
# crossbeam-queue = "0.3.12"
