[package]
name = "i_am_plugin"
version = "0.1.0"
edition = "2024"

[dependencies]
clack-extensions = { path = "../../clack/extensions", features = [
	"gui", "clack-plugin", "raw-window-handle_05", "audio-ports",
	"state", "params", "clap-wrapper", "latency", "note-ports"
] }
clack-plugin = { path = "../../clack/plugin" }
iced_baseview = { path = "../../iced_baseview" }
i_am_dsp = { workspace = true }
i_am_dsp_iced = { workspace = true }
raw-window-handle = { version = "0.5" }
crossbeam-channel = "0.5.15"
xxhash-rust = { version = "0.8.15", features = ["const_xxh3"] }
